apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: podinfo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: podinfo

  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          with:
            repoURL: https://github.com/AyanWarsame/Podinfo.git
            checkout:
              - branch: main
                path: repo

        - uses: kustomize-set-image
          with:
            path: repo/dev
            images:
              - image: ghcr.io/stefanprodan/podinfo
                tag: "{{ .Freight.Images[0].Tag }}"

        - uses: git-commit
          with:
            path: repo
            message: "update dev image"

        - uses: git-push
          with:
            path: repo
            targetBranch: main
